---
- name: Install apache2
  hosts: dbserver
  become: true

  tasks:
  - name: install apache2
    apt:
      name: apache2
  - name: start apache2 service
    service:
      name: apache2
      state: started
