---
- name: Tomcat installation
  hosts: all
  become: true

  tasks:
  - name: Install Java on Redhat Distributions
    yum:
      name: java
      state: installed
    when: ansible_os_family == "RedHat"

  - name: Install Java on Debian Distributions
    apt:
      name: default-jdk
      state: present
    when: ansible_os_family == "Debian"
  
  - name: Download Tomcat
    get_url:
      url: https://dlcdn.apache.org/tomcat/tomcat-8/v8.5.83/bin/apache-tomcat-8.5.83.tar.gz
      dest: /opt
  - name: Extract the tar file
    unarchive:
      src: /opt/apache-tomcat-8.5.83.tar.gz
      dest: /opt
      remote_src: yes
  - name: Change permissions
    file:
      path: /opt/apache-tomcat-8.5.83/bin/startup.sh
      mode: '0777'
  - name: Start tomcat server
    shell: nohup ./startup.sh
    args:
      chdir: /opt/apache-tomcat-8.5.83/bin
